-- ปรับตาราง accident ให้มีโครงสร้างตรงกับไฟล์ export ของระบบ 1669 ครบทั้ง 88 คอลัมน์
-- คอลัมน์เดิมที่ไฟล์ไม่มี (pname/fname/lname/drunk) คงไว้เพราะ UI ยังใช้ตัวกรองอยู่
DROP TABLE "accident";

CREATE TABLE "accident" (
    "id" SERIAL NOT NULL,
    "incident_no" VARCHAR(30),
    "op_no" VARCHAR(30),
    "command_province" TEXT,
    "command_center" TEXT,
    "incident_datetime" TIMESTAMPTZ(6) NOT NULL,
    "report_channel" TEXT,
    "reporter" TEXT,
    "reporter_phone" TEXT,
    "province" TEXT,
    "district" VARCHAR(100),
    "subdistrict" VARCHAR(100),
    "place" VARCHAR(255),
    "cbd" TEXT,
    "idc_code" TEXT,
    "phone_triage" TEXT,
    "rc_code" TEXT,
    "scene_triage" TEXT,
    "unit_code" TEXT,
    "unit_name" TEXT,
    "team_code" TEXT,
    "team_name" TEXT,
    "op_type" TEXT,
    "team_level" TEXT,
    "time_received" TIMESTAMPTZ(6),
    "time_dispatched" TIMESTAMPTZ(6),
    "time_departed_base" TIMESTAMPTZ(6),
    "time_arrived_scene" TIMESTAMPTZ(6),
    "time_left_scene" TIMESTAMPTZ(6),
    "time_arrived_hospital" TIMESTAMPTZ(6),
    "time_returned_base" TIMESTAMPTZ(6),
    "min_received_to_dispatch" INTEGER,
    "min_received_to_depart" INTEGER,
    "min_dispatch_to_depart" INTEGER,
    "min_received_to_scene" INTEGER,
    "min_scene_to_leave" INTEGER,
    "min_leave_to_hospital" INTEGER,
    "min_hospital_to_base" INTEGER,
    "km_received_to_scene" NUMERIC(14,3),
    "km_leave_to_hospital" NUMERIC(14,3),
    "km_hospital_to_base" NUMERIC(14,3),
    "op_result" TEXT,
    "patient_no" VARCHAR(30),
    "age_raw" TEXT,
    "gender" TEXT,
    "benefit_group" TEXT,
    "passport" TEXT,
    "benefit_type" TEXT,
    "other_insurance" TEXT,
    "benefit_country" TEXT,
    "vehicle_type" TEXT,
    "plate_category" TEXT,
    "plate_no" TEXT,
    "plate_province" TEXT,
    "patient_type" TEXT,
    "initial_care_result" TEXT,
    "hospital_code" TEXT,
    "transfer_criteria" TEXT,
    "summarizer_code" TEXT,
    "summarizer_name" TEXT,
    "hn" VARCHAR(50),
    "diagnosis" TEXT,
    "er_triage" TEXT,
    "airway" TEXT,
    "bleeding_control" TEXT,
    "iv_fluid" TEXT,
    "splinting" TEXT,
    "assessor" TEXT,
    "assessor_position" TEXT,
    "admitted" TEXT,
    "hospital_result" TEXT,
    "recorder" TEXT,
    "certifier" TEXT,
    "status" TEXT,
    "estimated_fee" NUMERIC(12,2),
    "distance_fee" NUMERIC(12,2),
    "consult_intake" TEXT,
    "consult_intake_doctor" TEXT,
    "consult_dispatch" TEXT,
    "consult_dispatch_doctor" TEXT,
    "consult_dispatch_note" TEXT,
    "consult_medical" TEXT,
    "consult_medical_doctor" TEXT,
    "consult_medical_note" TEXT,
    "lat" NUMERIC(9,6),
    "lon" NUMERIC(9,6),
    "crew_doctor" TEXT,
    "crew_nurse" TEXT,
    "crew_emt" TEXT,
    -- คอลัมน์เสริมนอกไฟล์ Excel
    "place_coordinate" geometry(Point, 4326),
    "triage" "triage",
    "pname" VARCHAR(50),
    "fname" VARCHAR(100),
    "lname" VARCHAR(100),
    "drunk" BOOLEAN,
    "source_file" TEXT,
    CONSTRAINT "accident_pkey" PRIMARY KEY ("id")
);

-- กันนำเข้าซ้ำ: 3 คอลัมน์นี้ unique 100% ทั้ง 13,468 แถวจาก 7 ไฟล์
CREATE UNIQUE INDEX "accident_op_patient_time_key" ON "accident" ("op_no", "patient_no", "incident_datetime");
CREATE INDEX "accident_place_coordinate_idx" ON "accident" USING GIST ("place_coordinate");
CREATE INDEX "accident_incident_datetime_idx" ON "accident" ("incident_datetime");
CREATE INDEX "accident_incident_no_idx" ON "accident" ("incident_no");
CREATE INDEX "accident_hn_idx" ON "accident" ("hn");
CREATE INDEX "accident_triage_idx" ON "accident" ("triage");
CREATE INDEX "accident_district_idx" ON "accident" ("district");
CREATE INDEX "accident_subdistrict_idx" ON "accident" ("subdistrict");
CREATE INDEX "accident_cbd_idx" ON "accident" ("cbd");
CREATE INDEX "accident_status_idx" ON "accident" ("status");
CREATE INDEX "accident_unit_name_idx" ON "accident" ("unit_name");
